
// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.20 - 15.20-p004_1
// Generated on: May 26 2024 11:47:55

// Verification Directory fv/synth_wrapper 

module counter(clk_i, rst_ni, sel_i, data_o);
  input clk_i, rst_ni, sel_i;
  output [3:0] data_o;
  wire clk_i, rst_ni, sel_i;
  wire [3:0] data_o;
  wire n_0, n_2, n_8, n_9, n_10, n_12, n_14, n_15;
  wire n_16, n_17, n_19, n_20, n_21, n_24, n_26, n_28;
  wire n_29, n_31, n_32, n_34, n_35, n_36, n_116, n_117;
  wire n_118, n_119, n_120, n_147, n_172, n_173, n_174, n_175;
  wire n_177, n_178;
  sky130_fd_sc_hd__dfxtp_4 \counter_q_reg[3] (.CLK (clk_i), .D (n_36),
       .Q (data_o[3]));
  sky130_fd_sc_hd__nand3_1 g2396(.A (n_35), .B (n_31), .C (n_178), .Y
       (n_36));
  sky130_fd_sc_hd__dfxtp_4 \counter_q_reg[1] (.CLK (clk_i), .D (n_32),
       .Q (data_o[1]));
  sky130_fd_sc_hd__nand4_1 g2398(.A (n_118), .B (n_29), .C (data_o[3]),
       .D (rst_ni), .Y (n_35));
  sky130_fd_sc_hd__dfxtp_4 \counter_q_reg[2] (.CLK (clk_i), .D (n_34),
       .Q (data_o[2]));
  sky130_fd_sc_hd__nand3_1 g2400(.A (n_26), .B (n_116), .C (n_24), .Y
       (n_34));
  sky130_fd_sc_hd__nand2_1 g2402(.A (n_28), .B (n_175), .Y (n_32));
  sky130_fd_sc_hd__nand3_1 g2403(.A (n_174), .B (n_17), .C (n_147), .Y
       (n_31));
  sky130_fd_sc_hd__nand4_1 g2405(.A (data_o[1]), .B (data_o[0]), .C
       (data_o[2]), .D (sel_i), .Y (n_29));
  sky130_fd_sc_hd__nand3b_1 g2406(.A_N (n_21), .B (n_177), .C (rst_ni),
       .Y (n_28));
  sky130_fd_sc_hd__nand3_1 g2408(.A (n_20), .B (n_119), .C (n_0), .Y
       (n_26));
  sky130_fd_sc_hd__nand4_1 g2410(.A (n_19), .B (n_177), .C (n_9), .D
       (n_8), .Y (n_24));
  sky130_fd_sc_hd__dfxtp_4 \counter_q_reg[0] (.CLK (clk_i), .D (n_19),
       .Q (data_o[0]));
  sky130_fd_sc_hd__nand3_1 g2414(.A (n_117), .B (n_2), .C (n_8), .Y
       (n_20));
  sky130_fd_sc_hd__nand2_1 g2415(.A (n_14), .B (n_16), .Y (n_21));
  sky130_fd_sc_hd__nand2_1 g2416(.A (n_120), .B (data_o[1]), .Y (n_16));
  sky130_fd_sc_hd__and2_4 g2417(.A (n_120), .B (rst_ni), .X (n_19));
  sky130_fd_sc_hd__nor2b_4 g2418(.A (n_10), .B_N (rst_ni), .Y (n_17));
  sky130_fd_sc_hd__nor2_1 g2419(.A (data_o[1]), .B (data_o[0]), .Y
       (n_15));
  sky130_fd_sc_hd__nand2_1 g2421(.A (n_8), .B (data_o[0]), .Y (n_14));
  sky130_fd_sc_hd__nor2_2 g2423(.A (n_2), .B (n_8), .Y (n_12));
  sky130_fd_sc_hd__inv_2 g2426(.A (n_9), .Y (n_10));
  sky130_fd_sc_hd__inv_2 g2427(.A (data_o[2]), .Y (n_9));
  sky130_fd_sc_hd__inv_4 g2429(.A (data_o[1]), .Y (n_8));
  sky130_fd_sc_hd__inv_1 g2440(.A (data_o[0]), .Y (n_2));
  sky130_fd_sc_hd__and2_4 g2(.A (rst_ni), .B (data_o[2]), .X (n_0));
  sky130_fd_sc_hd__nand2b_1 g2514(.A_N (n_119), .B (n_17), .Y (n_116));
  sky130_fd_sc_hd__nand4_2 g26(.A (n_117), .B (n_8), .C (n_9), .D
       (n_120), .Y (n_118));
  sky130_fd_sc_hd__clkinv_1 g27(.A (sel_i), .Y (n_117));
  sky130_fd_sc_hd__nand3_1 g19(.A (sel_i), .B (data_o[0]), .C
       (data_o[1]), .Y (n_119));
  sky130_fd_sc_hd__inv_2 g20(.A (data_o[0]), .Y (n_120));
  sky130_fd_sc_hd__buf_1 drc_bufs(.A (n_15), .X (n_147));
  sky130_fd_sc_hd__nor2_2 g2559(.A (data_o[3]), .B (n_173), .Y (n_174));
  sky130_fd_sc_hd__inv_4 g2560(.A (n_172), .Y (n_173));
  sky130_fd_sc_hd__inv_2 g2561(.A (sel_i), .Y (n_172));
  sky130_fd_sc_hd__nand3_1 g2562(.A (n_21), .B (n_173), .C (rst_ni), .Y
       (n_175));
  sky130_fd_sc_hd__inv_2 g2563(.A (n_173), .Y (n_177));
  sky130_fd_sc_hd__nand4b_1 g2564(.A_N (data_o[3]), .B (n_0), .C
       (n_12), .D (n_173), .Y (n_178));
endmodule

module synth_wrapper(sel_i, rst_n, clk, data_o);
  input sel_i, rst_n, clk;
  output [3:0] data_o;
  wire sel_i, rst_n, clk;
  wire [3:0] data_o;
  wire \data_o_reg[0]_14 , \data_o_reg[1]_15 , \data_o_reg[2]_16 ,
       \data_o_reg[3]_17 , sel_i_reg;
  counter u1(.clk_i (clk), .rst_ni (rst_n), .sel_i (sel_i_reg), .data_o
       ({\data_o_reg[3]_17 , \data_o_reg[2]_16 , \data_o_reg[1]_15 ,
       \data_o_reg[0]_14 }));
  sky130_fd_sc_hd__dfrtp_1 \data_o_reg[3] (.RESET_B (rst_n), .CLK
       (clk), .D (\data_o_reg[3]_17 ), .Q (data_o[3]));
  sky130_fd_sc_hd__dfrtp_1 \data_o_reg[2] (.RESET_B (rst_n), .CLK
       (clk), .D (\data_o_reg[2]_16 ), .Q (data_o[2]));
  sky130_fd_sc_hd__dfrtp_1 \data_o_reg[0] (.RESET_B (rst_n), .CLK
       (clk), .D (\data_o_reg[0]_14 ), .Q (data_o[0]));
  sky130_fd_sc_hd__dfrtp_1 \data_o_reg[1] (.RESET_B (rst_n), .CLK
       (clk), .D (\data_o_reg[1]_15 ), .Q (data_o[1]));
  sky130_fd_sc_hd__dfrtp_2 sel_i_reg_reg(.RESET_B (rst_n), .CLK (clk),
       .D (sel_i), .Q (sel_i_reg));
endmodule

