
// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.20 - 15.20-p004_1
// Generated on: May 26 2024 11:47:52

// Verification Directory fv/synth_wrapper 

module counter(clk_i, rst_ni, sel_i, data_o);
  input clk_i, rst_ni, sel_i;
  output [3:0] data_o;
  wire clk_i, rst_ni, sel_i;
  wire [3:0] data_o;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36;
  sky130_fd_sc_hd__dfxtp_4 \counter_q_reg[3] (.CLK (clk_i), .D (n_36),
       .Q (data_o[3]));
  sky130_fd_sc_hd__nand3_1 g2396(.A (n_35), .B (n_31), .C (n_33), .Y
       (n_36));
  sky130_fd_sc_hd__dfxtp_4 \counter_q_reg[1] (.CLK (clk_i), .D (n_32),
       .Q (data_o[1]));
  sky130_fd_sc_hd__nand4_1 g2398(.A (n_30), .B (n_29), .C (data_o[3]),
       .D (rst_ni), .Y (n_35));
  sky130_fd_sc_hd__dfxtp_4 \counter_q_reg[2] (.CLK (clk_i), .D (n_34),
       .Q (data_o[2]));
  sky130_fd_sc_hd__nand3_1 g2400(.A (n_26), .B (n_25), .C (n_24), .Y
       (n_34));
  sky130_fd_sc_hd__nand4b_1 g2401(.A_N (data_o[3]), .B (n_0), .C
       (n_12), .D (n_1), .Y (n_33));
  sky130_fd_sc_hd__nand2_1 g2402(.A (n_28), .B (n_27), .Y (n_32));
  sky130_fd_sc_hd__nand3_1 g2403(.A (n_13), .B (n_17), .C (n_15), .Y
       (n_31));
  sky130_fd_sc_hd__nand4_1 g2404(.A (n_5), .B (n_4), .C (n_9), .D
       (n_8), .Y (n_30));
  sky130_fd_sc_hd__nand4_1 g2405(.A (data_o[1]), .B (data_o[0]), .C
       (data_o[2]), .D (sel_i), .Y (n_29));
  sky130_fd_sc_hd__nand3b_1 g2406(.A_N (n_21), .B (n_7), .C (rst_ni),
       .Y (n_28));
  sky130_fd_sc_hd__nand3_1 g2407(.A (n_21), .B (n_1), .C (rst_ni), .Y
       (n_27));
  sky130_fd_sc_hd__nand3_1 g2408(.A (n_22), .B (n_20), .C (n_0), .Y
       (n_26));
  sky130_fd_sc_hd__nand2_1 g2409(.A (n_23), .B (n_17), .Y (n_25));
  sky130_fd_sc_hd__nand4_1 g2410(.A (n_19), .B (n_7), .C (n_11), .D
       (n_8), .Y (n_24));
  sky130_fd_sc_hd__inv_2 g2411(.A (n_22), .Y (n_23));
  sky130_fd_sc_hd__nand3_2 g2412(.A (n_3), .B (sel_i), .C (data_o[1]),
       .Y (n_22));
  sky130_fd_sc_hd__dfxtp_4 \counter_q_reg[0] (.CLK (clk_i), .D (n_19),
       .Q (data_o[0]));
  sky130_fd_sc_hd__nand3_1 g2414(.A (n_5), .B (n_2), .C (n_8), .Y
       (n_20));
  sky130_fd_sc_hd__nand2_1 g2415(.A (n_14), .B (n_16), .Y (n_21));
  sky130_fd_sc_hd__nand2_1 g2416(.A (n_4), .B (data_o[1]), .Y (n_16));
  sky130_fd_sc_hd__and2_4 g2417(.A (n_4), .B (rst_ni), .X (n_19));
  sky130_fd_sc_hd__nor2b_4 g2418(.A (n_10), .B_N (rst_ni), .Y (n_17));
  sky130_fd_sc_hd__nor2_1 g2419(.A (data_o[1]), .B (n_3), .Y (n_15));
  sky130_fd_sc_hd__nand2_2 g2421(.A (n_8), .B (data_o[0]), .Y (n_14));
  sky130_fd_sc_hd__nor2_2 g2422(.A (data_o[3]), .B (n_1), .Y (n_13));
  sky130_fd_sc_hd__nor2_1 g2423(.A (n_2), .B (n_8), .Y (n_12));
  sky130_fd_sc_hd__inv_1 g2425(.A (n_10), .Y (n_11));
  sky130_fd_sc_hd__inv_2 g2426(.A (n_9), .Y (n_10));
  sky130_fd_sc_hd__inv_2 g2427(.A (data_o[2]), .Y (n_9));
  sky130_fd_sc_hd__inv_6 g2429(.A (data_o[1]), .Y (n_8));
  sky130_fd_sc_hd__inv_2 g2431(.A (n_1), .Y (n_7));
  sky130_fd_sc_hd__inv_4 g2432(.A (n_6), .Y (n_1));
  sky130_fd_sc_hd__inv_2 g2433(.A (sel_i), .Y (n_6));
  sky130_fd_sc_hd__clkinv_1 g2434(.A (sel_i), .Y (n_5));
  sky130_fd_sc_hd__inv_2 g2436(.A (n_4), .Y (n_3));
  sky130_fd_sc_hd__inv_4 g2439(.A (data_o[0]), .Y (n_4));
  sky130_fd_sc_hd__inv_1 g2440(.A (data_o[0]), .Y (n_2));
  sky130_fd_sc_hd__and2_4 g2(.A (rst_ni), .B (data_o[2]), .X (n_0));
endmodule

module synth_wrapper(sel_i, rst_n, clk, data_o);
  input sel_i, rst_n, clk;
  output [3:0] data_o;
  wire sel_i, rst_n, clk;
  wire [3:0] data_o;
  wire \data_o_reg[0]_14 , \data_o_reg[1]_15 , \data_o_reg[2]_16 ,
       \data_o_reg[3]_17 , sel_i_reg;
  counter u1(.clk_i (clk), .rst_ni (rst_n), .sel_i (sel_i_reg), .data_o
       ({\data_o_reg[3]_17 , \data_o_reg[2]_16 , \data_o_reg[1]_15 ,
       \data_o_reg[0]_14 }));
  sky130_fd_sc_hd__dfrtp_1 \data_o_reg[3] (.RESET_B (rst_n), .CLK
       (clk), .D (\data_o_reg[3]_17 ), .Q (data_o[3]));
  sky130_fd_sc_hd__dfrtp_1 \data_o_reg[2] (.RESET_B (rst_n), .CLK
       (clk), .D (\data_o_reg[2]_16 ), .Q (data_o[2]));
  sky130_fd_sc_hd__dfrtp_1 \data_o_reg[0] (.RESET_B (rst_n), .CLK
       (clk), .D (\data_o_reg[0]_14 ), .Q (data_o[0]));
  sky130_fd_sc_hd__dfrtp_1 \data_o_reg[1] (.RESET_B (rst_n), .CLK
       (clk), .D (\data_o_reg[1]_15 ), .Q (data_o[1]));
  sky130_fd_sc_hd__dfrtp_2 sel_i_reg_reg(.RESET_B (rst_n), .CLK (clk),
       .D (sel_i), .Q (sel_i_reg));
endmodule

